### ISSUE TITLE
Crash when trying to load worlds that have been opened to LAN

### ISSUE THREAD

**Issue by MCgrs** [BigBastard/Valkyrien-Warfare-Revamped#14]
I don't know if you guys are already aware, but the latest release (0.86) causes a crash when loading a world that has previously been opened to LAN in a manner that resembles crashes caused by client-side only mods being run on a server.

Is the mod intended to be SMP/LAN incompatible? or am I simply doing something wrong to cause this?

below is a pastebin link with the crash log:

http://pastebin.com/GUpTDW5P

**Comment by DaMatrix** [comment]
Hmmm, looks interesting. Will try to fix it myself if @BigBastard doesn't get here first.
I'm running it on a dedicated server and it works fine, so it's probably something to do with open to LAN. Wil come back later with moar infoz.

**Comment by BigBastard** [comment]
Can you post the full log though?

**Comment by MCgrs** [comment]
do you mean the FML-client log?

http://pastebin.com/vYRZfvt5

**Comment by MCgrs** [comment]
If I start a new world and open it to LAN it doesn't crash when loading. It's only existing worlds. So I may have misdiagnosed this. It may be caused by items/blocks/entities from previous mods being placed in the world.

The crash log and FML-log are both from running the game with only this mod installed, although as the FML log shows the save was run previously with other mods on.

**Comment by DaMatrix** [comment]
The crash report doesn't show anything from Valkyrien Warfare.

**Comment by MCgrs** [comment]
But it only happens with it installed, also still happens with only it installed.

I can load the saves normally if I uninstall Valkyrian Warfare.

I thought given those facts I can assume it's caused by this mod.

**Comment by MCgrs** [comment]
sorry accidentally clicked close and comment earlier

**Comment by DaMatrix** [comment]
I use the same forge as is on the github,  as well as openjdk 8

**Comment by MCgrs** [comment]
Well a temporary solution that for some reason worked is removing them mod, loading into the world, executing /kill @e then installing the mod and the world loads normally.

**Comment by BigBastard** [comment]
Issues seems to be fixed in latest release, please tell us if issue persists in this version. https://jenkins.ironhide.de/job/Valkyrien-Warfare-Revamped/lastBuild/artifact/build/libs/ValkyrienWarfareRevamped-1.10.2-0.8.6d-23.jar

**Comment by BigBastard** [comment]
Ok, now it has to be fixed. I'm closing for now, lan worlds I tested were fine
