### ISSUE TITLE
Crash with PhysObjectRenderManager.updateRange()

### ISSUE THREAD

**Issue by BigBastard** [BigBastard/Valkyrien-Warfare-Revamped#19]
http://pastebin.com/tXqS5SuR

**Comment by DaMatrix** [comment]
Just for the sake of it,  try adding a model to the Ship Block Creative

**Comment by BigBastard** [comment]
Lol, fixed the crash and added the model for the sake of it 👍 

Its in a separate branch though, I might not release that for a few days

**Comment by BigBastard** [comment]
*Fixed in this https://github.com/BigBastard/Valkyrien-Warfare-Revamped/commit/8160073c6dd9d727432bc5bab230a4fe15c0b068
