### ISSUE TITLE
Serverside Crash

### ISSUE THREAD

**Issue by darklordwonton** [BigBastard/Valkyrien-Warfare-Revamped#2]
I posted this issue on the minecraft forums thread, I'm posting it here too for organization reasons:

Crashlog: http://pastebin.com/ANww3hQe, modlist is in the log I'm not sure what's causing the crash. I have personally modified Elements of Power to fix an issue the developer missed but it shouldn't have affected anything.

**Comment by BigBastard** [comment]
Fixed as of .86b, thanks for the report 👍
