### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by darklordwonton** [BigBastard/Valkyrien-Warfare-Revamped#26]
With the latest version I get this message spammed in the console whenever I make a new world: [Server thread/INFO]: [ValkyrienWarfareBase.PhysicsManagement.DimensionPhysObjectManager:getManagerForWorld:43]: getManagerForWorld just requested for a World without one!!! Wtf, how does this even Happen Man!?

**Comment by BigBastard** [comment]
Alright, I'll have it removed in the next commit pushed

**Comment by DaMatrix** [comment]
Should be fixed in #29

**Comment by BigBastard** [comment]
Fixed as of #29 (Thanks @DaMatrix)
